//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPUM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedbayContainer : DbContext
    {
        public MedbayContainer()
            : base("name=MedbayContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> CategorySet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<Price> PriceSet { get; set; }
        public virtual DbSet<Warehouse> WarehouseSet { get; set; }
        public virtual DbSet<Customer> CustomerSet { get; set; }
        public virtual DbSet<Adress> AdressSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Cart> CartSet { get; set; }
        public virtual DbSet<CartItem> CartItemSet { get; set; }
        public virtual DbSet<Order> OrderSet { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethodSet { get; set; }
        public virtual DbSet<TransportMethod> TransportMethodSet { get; set; }
    }
}
