//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string ShipNumber { get; set; }
        public string ShipCity { get; set; }
        public string ShipPostalCode { get; set; }
        public string CustomerComment { get; set; }
        public string UserComment { get; set; }
        public string Payments { get; set; }
        public int PaymentMethodId { get; set; }
        public int TransportMethodId { get; set; }
        public bool IsPaid { get; set; }
        public System.DateTime WasPaidAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string Net { get; set; }
        public string Gross { get; set; }
        public string Tax { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual TransportMethod TransportMethod { get; set; }
    }
}
